### ISSUE TITLE
Unable to verify Unreal EULA

### ISSUE THREAD

**Issue by MouseKeyboardController** [AchetaGames/Epic-Asset-Manager#251] opened 2024-03-20 21:28 UTC
**Describe the bug**
When attempting to verify the Unreal EULA, a top pops up in my browser, I accepted the EULA, but I still cannot install Unreal Engine. The button is grayed out.

**To Reproduce**
Click on the Green + that says Install Engine,
Click on the Life  Ring to sign the EULA
Sign the EULA
Re-open Epic Asset Manager, and the button is still grayed out. I clicked refresh in the top left, clicked revalidate next to the life ring, and even signed out and back in again and I am still unable to click the button.

**Expected behavior**
I expected to be able to download Unreal Engine after signing the EULA

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox
 - Version Debian 12

**Comment by aknarts** [comment] 2024-03-21 10:55
Duplicate of #249, sadly Epic did lock down the verification there, so far I have not been able to bypass it, though I do have a "workaround" in the works, need to figure out last couple bits. I will close this in favour of the other issue.

**Closed as completed by aknarts** 2024-03-21 10:55 UTC
