### ISSUE TITLE
Plugins stuck on `Initalizing...`

### ISSUE THREAD

**Issue by d3kryption** [AchetaGames/Epic-Asset-Manager#252] opened 2024-04-03 20:54 UTC
**Describe the bug**
Hey!
Love this app. Used it for years. However, recently a lot of plugins just keep being stuck on `Initalizing...`. I've left them for 20 minutes and it just doesn't move. I go back into Windows and it downloads straight away from the Epic Launcher. 
When its stuck in this mode I can't cancel it. I just have to quit the app and open it back up.

I've tired a few plugins. Some work others don't. I've checked and the platforms do support Linux

Also tried reinstalling and logging out and back in.

If there is anything else I can provide please let me know :)

Note, I contacted Epic and asked if it was their issue. They claimed its all good from their side.

Its been like this for nearly 2 months now.

** LOG **
Running via terminal I get this: (I removed the two identifiers because I don't know if they are meant to stay secret)

```
    ~  /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=epic_asset_manager --file-forwarding io.github.achetagames.epic_asset_manager RUST_BACKTRACE=1
<epic_asset_manager> - [DEBUG] - /app/share/epic_asset_manager
<epic_asset_manager> - [DEBUG] - 
<epic_asset_manager> - [DEBUG] - 3.8.4
<epic_asset_manager::application> - [INFO] - Epic Asset Manager (io.github.achetagames.epic_asset_manager)
<epic_asset_manager::application> - [INFO] - Version: 3.8.4 ()
<epic_asset_manager::application> - [INFO] - Datadir: /app/share/epic_asset_manager
<epic_asset_manager::application::imp> - [DEBUG] - GtkApplication<EpicAssetManager>::startup
<epic_asset_manager::tools::epic_web> - [ERROR] - Error parsing json: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
<epic_asset_manager::tools::epic_web> - [ERROR] - Failed to query EULA status: EulaQuery/hasAccountAccepted: Request failed with status code 401 with response: {"errorCode":"errors.com.epicgames.common.authentication.authentication_failed","errorMessage":"Authentication failed for /api/public/agreements/unreal_engine/identities/IDENTIFER_REMOVED","messageVars":["/api/public/agreements/unreal_engine/identities/IDENTIFER_REMOVED"],"numericErrorCode":1032,"originatingService":"com.epicgames.eulatracking.public","intent":"prod","errorStatus":401}
thread 'Download Pool' panicked at 'range end index 225025 out of range for slice of length 225023', /run/build/epic_asset_manager/vendor/egs-api/src/api/utils.rs:43:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Download Pool' panicked at 'range end index 225025 out of range for slice of length 225023', /run/build/epic_asset_manager/vendor/egs-api/src/api/utils.rs:43:24
    ~   
 ```

**To Reproduce**
Steps to reproduce the behaviour:
1.  Load Epic Asset Manager
2. Try to download some plugins

**Expected behavior**
When downloading the plugins it should stick on Initalizing for a moment, then proceed to downloading, then complete

**Screenshots**
![image](https://github.com/AchetaGames/Epic-Asset-Manager/assets/48034534/b6c7a938-c401-434a-ba2f-9825bc8d2220)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - App Version: 3.8.4 

Thank you! :D

**Comment by d-potrivaev** [comment] 2024-04-04 10:47
Hi guys,
Having absolutely the same issue with downloading another asset I bought: https://www.unrealengine.com/marketplace/en-US/product/pcg-river-biome-generator-interactive-foliage-tree-water

I am also stuck on the Initialization step... Other assets I have in the Library downloading without any problem. I can download this asset on my friend's PC under Windows with the official Launcher and in my account. So, I also suppose the issue is related to Epic Asset Manager (EAM) only.

One thing I also noticed is the estimated asset size in EAM also can't be calculated.

I'm not sure if it helps, but this "problem" asset was released in March 2024. So, it's pretty fresh. All my other assets have a release date in 2023 and even earlier. So, just a thought, maybe it's related to new assets only? Maybe something was changed in the Unreal Market?

- OS: Linux Mint 21.3
- App Ver: 3.8.4 

Thanks for your support, guys, and let me say a huge THANK YOU for your hard work in providing the Linux community with a great tool for UE users!!! I very much appreciate it!

**Comment by aknarts** [comment] 2024-04-04 12:59
They do seem to have changed some format, do you have examples of the assets that are failing? If they were in some of the free ones it would be ideal.

**Comment by d-potrivaev** [comment] 2024-04-04 13:22
Please check this one: https://www.unrealengine.com/marketplace/en-US/product/gregstr-s-importer

I've found it in Marketplace and it's free now. Also, it's fresh (was published a day ago) and I have the same problem with it. I hope it will help!

P.S. Thanks for your fast reply!

**Comment by aknarts** [comment] 2024-04-04 14:53
Thank you, it will take me a bit to debug this, but having a test asset helps big time. I suspect they added a field or made one not mandatory and it would affect any new uploads. I hope I get to this over the weekend. I also have couple other things in the work for this project so need to push it through.

**Comment by Calavera00** [comment] 2024-04-16 01:28
Hi all, having this same issue with the official Metahumans plugin. I appreciate the work you are doing, just found out about EAM and love it
https://www.unrealengine.com/marketplace/en-US/product/metahuman-plugin

**Comment by ProfessorSalty** [comment] 2024-04-26 19:39
Hello,

Just adding the [Lyra starter game](https://www.unrealengine.com/marketplace/en-US/product/lyra) to the list of plugins that sit on 'Initializing...'

Also a big fan of the app! Thanks for making my life easier!

**Comment by aknarts** [comment] 2024-05-09 22:33
Surprisingly after some while I did actually make progress on this. They did seem to switch from json format to binary format for the Unreal assets, which would not be an issue, but at the same time they changed the format of that binary. I do have an example so it is only a matter of time to debug this. I hope.

**Closed** 2024-05-09 23:54 UTC
